#deploy tomcat 
- name: copy_tomcat_package
  copy:
    src: apache-tomcat-{{ tomcat_version }}.tar.gz 
    dest: /data

- name: unzip_package
  shell: cd /data && tar -xf apache-tomcat-{{ tomcat_version }}.tar.gz && mv apache-tomcat-{{ tomcat_version }} tomcat

- name: setup_tomcat_dir
  shell: chown tomcat:tomcat -R /data/tomcat

- name: copy_tomcat_service_file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systemd"

- name: start_and_enable_tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

- name: remove_tomcat_package
  file: path=/data/apache-tomcat-{{ tomcat_version }}.tar.gz state=absent

- name: custom_catalina
  template:
    src: catalina.sh.j2
    dest: /data/tomcat/bin/catalina.sh
  notify: restart tomcat
